# Installs the Oracle Java development kit package from RHEL repositories.
# Includes unlimited JCE policy files for added security. Uses alternatives to set java defaults.
# Requires setting the oracle_java_version var (1.7.0, 1.8.0, etc)

- name: Install Oracle JDK RPM
  yum: pkg="java-{{ oracle_java_version }}-oracle-devel" state=present
  sudo: yes
  tags:
    - install
    - upgrade

# For some reason in my testing on RHEL6 the alternatives command for keytool will fail if this file already exists.
- name: Remove existing keytool Alternatives File
  file: path=/var/lib/alternatives/keytool state=absent
  sudo: yes
  tags:
    - install
    - upgrade

- name: Set Java defaults
  alternatives:
    name="{{ item.exe }}"
    link="/usr/bin/{{ item.exe }}"
    path="{{ item.path }}/{{ item.exe }}"
  with_items:
    - { path: "/usr/lib/jvm/java-{{ oracle_java_version }}-oracle.x86_64/jre/bin", exe: 'java' }
    - { path: "/usr/lib/jvm/java-{{ oracle_java_version }}-oracle.x86_64/jre/bin", exe: 'keytool' }
    - { path: "/usr/lib/jvm/java-{{ oracle_java_version }}-oracle.x86_64/bin", exe: 'javac' }
    - { path: "/usr/lib/jvm/java-{{ oracle_java_version }}-oracle.x86_64/bin", exe: 'javadoc' }
  sudo: yes
  tags:
    - install
    - upgrade

- name: Set Default JRE
  alternatives:
    name="jre_oracle"
    path="/usr/lib/jvm/jre-{{ oracle_java_version }}-oracle.x86_64"
  sudo: yes
  tags:
    - install
    - upgrade

- name: Create Unlimited JCE Policy Custom Directory
  file: path=/usr/lib/jvm-private/oracle/jce/unlimited mode=0755 owner=root state=directory
  sudo: yes
  tags:
    - install
    - upgrade
- name: Copy Unlimited JCE Policy files
  copy: src={{ item.src }} dest={{ item.dest }} owner=root
  with_items:
    - { src: "{{ jce_policy_files_path }}/{{ jce_us_export_policy_filename }}",
        dest: '/usr/lib/jvm-private/oracle/jce/unlimited/US_export_policy.jar' }
    - { src: "{{ jce_policy_files_path }}/{{ jce_local_policy_filename }}",
        dest: '/usr/lib/jvm-private/oracle/jce/unlimited/local_policy.jar' }
  sudo: yes
  tags:
    - install
    - upgrade

- name: Set JCE Policy files as defaults
  command: >
    /usr/sbin/update-alternatives --install
    /usr/lib/jvm/jre-{{ oracle_java_version }}-oracle.x86_64/lib/security/local_policy.jar
    jce_{{ oracle_java_version }}_oracle_local_policy.x86_64
    /usr/lib/jvm-private/oracle/jce/unlimited/local_policy.jar
    900000
    --slave
    /usr/lib/jvm/jre-{{ oracle_java_version }}-oracle.x86_64/lib/security/US_export_policy.jar
    jce_{{ oracle_java_version }}_oracle_us_export_policy.x86_64
    /usr/lib/jvm-private/oracle/jce/unlimited/US_export_policy.jar
  sudo: yes
  tags:
    - install
    - upgrade
